services:
  miskatonicassistant:
    image: miskatonicassistant
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - CDN_ROOT=https://thisisfine.au/cdn
